server:
  port: 9000

spring:
  application:
    name: flashsale-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user
          uri: lb://flashsale-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: product
          uri: lb://flashsale-product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: order
          uri: lb://flashsale-order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: payment
          uri: lb://flashsale-payment-service
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1