server:
  port: 9030

spring:
  application:
    name: flashsale-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fs_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: whc7777777

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated   # 生产端 Confirm
    publisher-returns: true              # 生产端 Return
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual         # 消费端手动 ack
        default-requeue-rejected: false  # 业务异常不回原队列，交给 DLX/重试队列
        prefetch: 100                    # 每次预取
        concurrency: 2                   # 并发消费者数
        max-concurrency: 8

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    openfeign:
      # === 选用 Apache HttpClient（feign-httpclient） ===
      httpclient:
        hc5:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ye94z.order.entity
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.ye94z.order: warn
    org.apache.hc.client5.http: INFO   # 如果走HC5
    # 若需排查 Feign 问题，可临时打开：
    # feign: DEBUG
    # org.springframework.cloud.openfeign: DEBUG