server:
  port: 9030

spring:
  application:
    name: flashsale-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fs_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: whc7777777

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated   # 生产端 Confirm
    publisher-returns: true              # 生产端 Return
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual         # 消费端手动 ack
        default-requeue-rejected: false # <<< 业务异常抛出后不回原队列，交给 DLX/重试队列
        prefetch: 100                   # 每次拉取多少条，视并发与业务耗时调
        concurrency: 2                  # 并发消费者数
        max-concurrency: 8

  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ye94z.order.entity
  configuration:
    map-underscore-to-camel-case: true
    # 打印SQL（开发阶段可开）
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ye94z.order: INFO

